# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portsweep < Formula
  desc "TUI for managing processes listening on ports"
  homepage "https://github.com/jillesme/portsweep"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/jillesme/portsweep/releases/download/v0.1.0/portsweep_darwin_all.tar.gz"
  sha256 "b8b17e28f4df35e754c534653272eeebc8a954f199ed5fc40c02bb0a8ecd57dc"

  def install
    bin.install "portsweep"
  end

  test do
    system "#{bin}/portsweep", "--version"
  end
end
